version: "3"
services:
  authority:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/authority.toml
      --engine-signer ${SIGNER_ADDRESS}
      --jsonrpc-port=${RPC_PORT}
      --ws-port=854${ID}
      --jsonrpc-interface all
      --port=3030${ID}
    ports:
      - ${RPC_PORT}:${RPC_PORT}
