version: "3"
services:
  authority:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/authority.toml
      --engine-signer ${SIGNER_ADDRESS}
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
      # TODO: make ports also dynamic with env file
