version: "3"
services:
  authority:
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
    command: --config /parity/config/authority.toml
      --engine-signer ${SIGNER_ADDRESS}
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --jsonrpc-port=${RPC_PORT}
    ports:
      - ${RPC_PORT}:${RPC_PORT}
