[parity]
chain = "chain/spec-1.json"
base_path = "/tmp/parity/auth2"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8452