[parity]
chain = "chain/spec-1.json"
base_path = "/tmp/parity/auth1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8451