version: "3"
services:
  authority0:
    build:
      context: .
      dockerfile: sealer_docker/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 0
    # volumes:
    #   - ./data-volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command: --config /parity/config/authority.toml
      --engine-signer 0x82f876d4bbb1b017e0d730f12d9721e0a2b1fe16
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303

  authority1:
    build:
      context: .
      dockerfile: sealer_docker/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 1
    command: --config /parity/config/authority.toml
      --engine-signer 0x98b32c998f16e36cff94b430c656335d682e78dd
      --no-persistent-txqueue
      --fast-unlock
