[parity]
chain = "chain/spec-1.json"
base_path = "/tmp/parity/auth3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8453