[parity]
chain = "chain/spec-2.json"
base_path = "/tmp/parity/auth3"
[network]
port = 30303
[rpc]
port = 8543
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8453
[account]
password = ["nodes/local/auth3/node.pwd"]
[mining]
engine_signer = "0x00373f0317411aa5cc7a4005c67bacc3c5c4e7c9"
reseal_on_txs = "none"