version: "3.7"

services:
  backend:
    build: ./
    environment:
      - IDENTITY_PROVIDER_BACKEND_PORT=${IDENTITY_PROVIDER_BACKEND_PORT}
      - IDENTITY_PROVIDER_BACKEND_IP=${IDENTITY_PROVIDER_BACKEND_IP}
      - ACCESS_PROVIDER_BACKEND_PORT=${ACCESS_PROVIDER_BACKEND_PORT}
      - ACCESS_PROVIDER_BACKEND_IP=${ACCESS_PROVIDER_BACKEND_IP}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${IDENTITY_PROVIDER_BACKEND_PORT}:${IDENTITY_PROVIDER_BACKEND_PORT}
    volumes:
      - ./src:/usr/src/backend/src
    networks:
      e-voting:
        ipv4_address: ${IDENTITY_PROVIDER_BACKEND_IP}
    command: npm run serve:dev:clean

networks:
  e-voting:
    external: true
