[parity]
chain = "/parity/config/chain.json"

[network]
port = 30301

[rpc]
cors = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[account]
password = ["/parity/config/authority.pwd"]

[mining]
reseal_on_txs = "none"
usd_per_tx = "0"
