version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/crypto"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_type: "direct"
          update_type: "all"
