[parity]
chain = "chain/spec-2.json"
base_path = "/tmp/parity/user"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["nodes/local/user/node.pwd"]
[mining]
engine_signer = "0x004ec07d2329997267ec62b4166639513386f32e"
reseal_on_txs = "none"